### ISSUE TITLE
درخواست راهنما و دمو

### ISSUE THREAD

**Issue by zoghal** [IKAcc/Pol#2]
جاوید جان خیلی‌ها مثل من زیاد با خوندن متن انگلیسی یا مثال کوتاه، نمی‌تونند سریع متوجه به شوند که داستان چیه، پیشنهاد می‌کنم یک دمو نمایشی/ آموزشی سادی اضافه کنید.

**Comment by Javid-Izadfar** [comment]
سلام صالح جان

کاملا حق با شما هست! ما یه سایت هم براش داشتیم درست میکردیم ولی واقعا یادم نمیاد برای چی نهایی نشد.
خوب شد که شما بهش اشاره‌ای کردی!

انشالا این پنجشنبه و جمعه، هم دمو رو بالا میارم

**Comment by zoghal** [comment]
مخلصیم آقا عجله نکن که کار شیطونه :دی
